name: Renovate
on:
  schedule:
    - cron: "0/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.3
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
