name: Renovate
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.3
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
